package com.asher.blog.entity;

import java.io.Serializable;

public class BlogArticleContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_content.ART_ID
     *
     * @mbggenerated
     */
    private String artId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_content.ART_CONTENT
     *
     * @mbggenerated
     */
    private String artContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_content.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    private String artOriContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_content.ART_ID
     *
     * @return the value of blog_article_content.ART_ID
     *
     * @mbggenerated
     */
    public String getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_content.ART_ID
     *
     * @param artId the value for blog_article_content.ART_ID
     *
     * @mbggenerated
     */
    public void setArtId(String artId) {
        this.artId = artId == null ? null : artId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_content.ART_CONTENT
     *
     * @return the value of blog_article_content.ART_CONTENT
     *
     * @mbggenerated
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_content.ART_CONTENT
     *
     * @param artContent the value for blog_article_content.ART_CONTENT
     *
     * @mbggenerated
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent == null ? null : artContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_content.ART_ORI_CONTENT
     *
     * @return the value of blog_article_content.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    public String getArtOriContent() {
        return artOriContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_content.ART_ORI_CONTENT
     *
     * @param artOriContent the value for blog_article_content.ART_ORI_CONTENT
     *
     * @mbggenerated
     */
    public void setArtOriContent(String artOriContent) {
        this.artOriContent = artOriContent == null ? null : artOriContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlogArticleContent other = (BlogArticleContent) that;
        return (this.getArtId() == null ? other.getArtId() == null : this.getArtId().equals(other.getArtId()))
            && (this.getArtContent() == null ? other.getArtContent() == null : this.getArtContent().equals(other.getArtContent()))
            && (this.getArtOriContent() == null ? other.getArtOriContent() == null : this.getArtOriContent().equals(other.getArtOriContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArtId() == null) ? 0 : getArtId().hashCode());
        result = prime * result + ((getArtContent() == null) ? 0 : getArtContent().hashCode());
        result = prime * result + ((getArtOriContent() == null) ? 0 : getArtOriContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", artId=").append(artId);
        sb.append(", artContent=").append(artContent);
        sb.append(", artOriContent=").append(artOriContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}