package com.asher.blog.entity;

import java.io.Serializable;
import java.util.Date;

public class BlogArticleCorpus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.COR_ID
     *
     * @mbggenerated
     */
    private String corId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.COR_NAME
     *
     * @mbggenerated
     */
    private String corName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    private Date lastModTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article_corpus
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.COR_ID
     *
     * @return the value of blog_article_corpus.COR_ID
     *
     * @mbggenerated
     */
    public String getCorId() {
        return corId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.COR_ID
     *
     * @param corId the value for blog_article_corpus.COR_ID
     *
     * @mbggenerated
     */
    public void setCorId(String corId) {
        this.corId = corId == null ? null : corId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.COR_NAME
     *
     * @return the value of blog_article_corpus.COR_NAME
     *
     * @mbggenerated
     */
    public String getCorName() {
        return corName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.COR_NAME
     *
     * @param corName the value for blog_article_corpus.COR_NAME
     *
     * @mbggenerated
     */
    public void setCorName(String corName) {
        this.corName = corName == null ? null : corName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.USER_ID
     *
     * @return the value of blog_article_corpus.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.USER_ID
     *
     * @param userId the value for blog_article_corpus.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.CREATE_TIME
     *
     * @return the value of blog_article_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.CREATE_TIME
     *
     * @param createTime the value for blog_article_corpus.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.STATUS
     *
     * @return the value of blog_article_corpus.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.STATUS
     *
     * @param status the value for blog_article_corpus.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article_corpus.LAST_MOD_TIME
     *
     * @return the value of blog_article_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public Date getLastModTime() {
        return lastModTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article_corpus.LAST_MOD_TIME
     *
     * @param lastModTime the value for blog_article_corpus.LAST_MOD_TIME
     *
     * @mbggenerated
     */
    public void setLastModTime(Date lastModTime) {
        this.lastModTime = lastModTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_corpus
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlogArticleCorpus other = (BlogArticleCorpus) that;
        return (this.getCorId() == null ? other.getCorId() == null : this.getCorId().equals(other.getCorId()))
            && (this.getCorName() == null ? other.getCorName() == null : this.getCorName().equals(other.getCorName()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastModTime() == null ? other.getLastModTime() == null : this.getLastModTime().equals(other.getLastModTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_corpus
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCorId() == null) ? 0 : getCorId().hashCode());
        result = prime * result + ((getCorName() == null) ? 0 : getCorName().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastModTime() == null) ? 0 : getLastModTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_corpus
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", corId=").append(corId);
        sb.append(", corName=").append(corName);
        sb.append(", userId=").append(userId);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", lastModTime=").append(lastModTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}