package com.asher.blog.entity;

import java.io.Serializable;
import java.util.Date;

public class BlogTag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tag.INDEX
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_tag
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.TAG_ID
     *
     * @return the value of blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.TAG_ID
     *
     * @param tagId the value for blog_tag.TAG_ID
     *
     * @mbggenerated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.TAG_NAME
     *
     * @return the value of blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.TAG_NAME
     *
     * @param tagName the value for blog_tag.TAG_NAME
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.CREATE_TIME
     *
     * @return the value of blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.CREATE_TIME
     *
     * @param createTime the value for blog_tag.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tag.INDEX
     *
     * @return the value of blog_tag.INDEX
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tag.INDEX
     *
     * @param index the value for blog_tag.INDEX
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_tag
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlogTag other = (BlogTag) that;
        return (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()))
            && (this.getTagName() == null ? other.getTagName() == null : this.getTagName().equals(other.getTagName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIndex() == null ? other.getIndex() == null : this.getIndex().equals(other.getIndex()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_tag
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
        result = prime * result + ((getTagName() == null) ? 0 : getTagName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIndex() == null) ? 0 : getIndex().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_tag
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tagId=").append(tagId);
        sb.append(", tagName=").append(tagName);
        sb.append(", createTime=").append(createTime);
        sb.append(", index=").append(index);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}