package com.asher.blog.entity;

import java.io.Serializable;
import java.util.Date;

public class SysDataDic extends SysDataDicKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    private String dicValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    private String dicDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.DIC_VALUE
     *
     * @return the value of sys_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.DIC_VALUE
     *
     * @param dicValue the value for sys_data_dic.DIC_VALUE
     *
     * @mbggenerated
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.DIC_DESC
     *
     * @return the value of sys_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    public String getDicDesc() {
        return dicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.DIC_DESC
     *
     * @param dicDesc the value for sys_data_dic.DIC_DESC
     *
     * @mbggenerated
     */
    public void setDicDesc(String dicDesc) {
        this.dicDesc = dicDesc == null ? null : dicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.CREATE_TIME
     *
     * @return the value of sys_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.CREATE_TIME
     *
     * @param createTime the value for sys_data_dic.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.MOD_TIME
     *
     * @return the value of sys_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.MOD_TIME
     *
     * @param modTime the value for sys_data_dic.MOD_TIME
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDataDic other = (SysDataDic) that;
        return (this.getDicGroup() == null ? other.getDicGroup() == null : this.getDicGroup().equals(other.getDicGroup()))
            && (this.getDicKey() == null ? other.getDicKey() == null : this.getDicKey().equals(other.getDicKey()))
            && (this.getDicValue() == null ? other.getDicValue() == null : this.getDicValue().equals(other.getDicValue()))
            && (this.getDicDesc() == null ? other.getDicDesc() == null : this.getDicDesc().equals(other.getDicDesc()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModTime() == null ? other.getModTime() == null : this.getModTime().equals(other.getModTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDicGroup() == null) ? 0 : getDicGroup().hashCode());
        result = prime * result + ((getDicKey() == null) ? 0 : getDicKey().hashCode());
        result = prime * result + ((getDicValue() == null) ? 0 : getDicValue().hashCode());
        result = prime * result + ((getDicDesc() == null) ? 0 : getDicDesc().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModTime() == null) ? 0 : getModTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicValue=").append(dicValue);
        sb.append(", dicDesc=").append(dicDesc);
        sb.append(", createTime=").append(createTime);
        sb.append(", modTime=").append(modTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}