package com.alance.blog.mapper;

import com.alance.blog.entity.SysDataDic;
import com.alance.blog.entity.SysDataDicExample;
import com.alance.blog.entity.SysDataDicKey;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * @author alance
 */
@Repository
public interface SysDataDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int countByExample(SysDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int deleteByExample(SysDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysDataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int insert(SysDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int insertSelective(SysDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    List<SysDataDic> selectByExample(SysDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    SysDataDic selectByPrimaryKey(SysDataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysDataDic record, @Param("example") SysDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysDataDic record, @Param("example") SysDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysDataDic record);
}