package com.alance.blog.entity;

import java.io.Serializable;
import java.util.Date;

public class BlogArticle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_ID
     *
     * @mbggenerated
     */
    private String artId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_NAME
     *
     * @mbggenerated
     */
    private String artName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_SHORT
     *
     * @mbggenerated
     */
    private String artShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.LAST_MODE_TIME
     *
     * @mbggenerated
     */
    private Date lastModeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.APPROVE_STATUS
     *
     * @mbggenerated
     */
    private Integer approveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.CORPUS_ID
     *
     * @mbggenerated
     */
    private String corpusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.READ_TIMES
     *
     * @mbggenerated
     */
    private Integer readTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.COMMENT_TIMES
     *
     * @mbggenerated
     */
    private Integer commentTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ADMIRE_TIMES
     *
     * @mbggenerated
     */
    private Integer admireTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.PUBLISH_STATUS
     *
     * @mbggenerated
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.PUBLISH_TIME
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ART_SHORT_PIC
     *
     * @mbggenerated
     */
    private String artShortPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.EDITOR_TYPE
     *
     * @mbggenerated
     */
    private Integer editorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_ID
     *
     * @return the value of blog_article.ART_ID
     *
     * @mbggenerated
     */
    public String getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_ID
     *
     * @param artId the value for blog_article.ART_ID
     *
     * @mbggenerated
     */
    public void setArtId(String artId) {
        this.artId = artId == null ? null : artId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_NAME
     *
     * @return the value of blog_article.ART_NAME
     *
     * @mbggenerated
     */
    public String getArtName() {
        return artName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_NAME
     *
     * @param artName the value for blog_article.ART_NAME
     *
     * @mbggenerated
     */
    public void setArtName(String artName) {
        this.artName = artName == null ? null : artName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_SHORT
     *
     * @return the value of blog_article.ART_SHORT
     *
     * @mbggenerated
     */
    public String getArtShort() {
        return artShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_SHORT
     *
     * @param artShort the value for blog_article.ART_SHORT
     *
     * @mbggenerated
     */
    public void setArtShort(String artShort) {
        this.artShort = artShort == null ? null : artShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.CREATE_TIME
     *
     * @return the value of blog_article.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.CREATE_TIME
     *
     * @param createTime the value for blog_article.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.LAST_MODE_TIME
     *
     * @return the value of blog_article.LAST_MODE_TIME
     *
     * @mbggenerated
     */
    public Date getLastModeTime() {
        return lastModeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.LAST_MODE_TIME
     *
     * @param lastModeTime the value for blog_article.LAST_MODE_TIME
     *
     * @mbggenerated
     */
    public void setLastModeTime(Date lastModeTime) {
        this.lastModeTime = lastModeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.STATUS
     *
     * @return the value of blog_article.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.STATUS
     *
     * @param status the value for blog_article.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.APPROVE_STATUS
     *
     * @return the value of blog_article.APPROVE_STATUS
     *
     * @mbggenerated
     */
    public Integer getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.APPROVE_STATUS
     *
     * @param approveStatus the value for blog_article.APPROVE_STATUS
     *
     * @mbggenerated
     */
    public void setApproveStatus(Integer approveStatus) {
        this.approveStatus = approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.USER_ID
     *
     * @return the value of blog_article.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.USER_ID
     *
     * @param userId the value for blog_article.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.CORPUS_ID
     *
     * @return the value of blog_article.CORPUS_ID
     *
     * @mbggenerated
     */
    public String getCorpusId() {
        return corpusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.CORPUS_ID
     *
     * @param corpusId the value for blog_article.CORPUS_ID
     *
     * @mbggenerated
     */
    public void setCorpusId(String corpusId) {
        this.corpusId = corpusId == null ? null : corpusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.READ_TIMES
     *
     * @return the value of blog_article.READ_TIMES
     *
     * @mbggenerated
     */
    public Integer getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.READ_TIMES
     *
     * @param readTimes the value for blog_article.READ_TIMES
     *
     * @mbggenerated
     */
    public void setReadTimes(Integer readTimes) {
        this.readTimes = readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.COMMENT_TIMES
     *
     * @return the value of blog_article.COMMENT_TIMES
     *
     * @mbggenerated
     */
    public Integer getCommentTimes() {
        return commentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.COMMENT_TIMES
     *
     * @param commentTimes the value for blog_article.COMMENT_TIMES
     *
     * @mbggenerated
     */
    public void setCommentTimes(Integer commentTimes) {
        this.commentTimes = commentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ADMIRE_TIMES
     *
     * @return the value of blog_article.ADMIRE_TIMES
     *
     * @mbggenerated
     */
    public Integer getAdmireTimes() {
        return admireTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ADMIRE_TIMES
     *
     * @param admireTimes the value for blog_article.ADMIRE_TIMES
     *
     * @mbggenerated
     */
    public void setAdmireTimes(Integer admireTimes) {
        this.admireTimes = admireTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.PUBLISH_STATUS
     *
     * @return the value of blog_article.PUBLISH_STATUS
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.PUBLISH_STATUS
     *
     * @param publishStatus the value for blog_article.PUBLISH_STATUS
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.PUBLISH_TIME
     *
     * @return the value of blog_article.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.PUBLISH_TIME
     *
     * @param publishTime the value for blog_article.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ART_SHORT_PIC
     *
     * @return the value of blog_article.ART_SHORT_PIC
     *
     * @mbggenerated
     */
    public String getArtShortPic() {
        return artShortPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ART_SHORT_PIC
     *
     * @param artShortPic the value for blog_article.ART_SHORT_PIC
     *
     * @mbggenerated
     */
    public void setArtShortPic(String artShortPic) {
        this.artShortPic = artShortPic == null ? null : artShortPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.EDITOR_TYPE
     *
     * @return the value of blog_article.EDITOR_TYPE
     *
     * @mbggenerated
     */
    public Integer getEditorType() {
        return editorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.EDITOR_TYPE
     *
     * @param editorType the value for blog_article.EDITOR_TYPE
     *
     * @mbggenerated
     */
    public void setEditorType(Integer editorType) {
        this.editorType = editorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlogArticle other = (BlogArticle) that;
        return (this.getArtId() == null ? other.getArtId() == null : this.getArtId().equals(other.getArtId()))
            && (this.getArtName() == null ? other.getArtName() == null : this.getArtName().equals(other.getArtName()))
            && (this.getArtShort() == null ? other.getArtShort() == null : this.getArtShort().equals(other.getArtShort()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModeTime() == null ? other.getLastModeTime() == null : this.getLastModeTime().equals(other.getLastModeTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getApproveStatus() == null ? other.getApproveStatus() == null : this.getApproveStatus().equals(other.getApproveStatus()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCorpusId() == null ? other.getCorpusId() == null : this.getCorpusId().equals(other.getCorpusId()))
            && (this.getReadTimes() == null ? other.getReadTimes() == null : this.getReadTimes().equals(other.getReadTimes()))
            && (this.getCommentTimes() == null ? other.getCommentTimes() == null : this.getCommentTimes().equals(other.getCommentTimes()))
            && (this.getAdmireTimes() == null ? other.getAdmireTimes() == null : this.getAdmireTimes().equals(other.getAdmireTimes()))
            && (this.getPublishStatus() == null ? other.getPublishStatus() == null : this.getPublishStatus().equals(other.getPublishStatus()))
            && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
            && (this.getArtShortPic() == null ? other.getArtShortPic() == null : this.getArtShortPic().equals(other.getArtShortPic()))
            && (this.getEditorType() == null ? other.getEditorType() == null : this.getEditorType().equals(other.getEditorType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArtId() == null) ? 0 : getArtId().hashCode());
        result = prime * result + ((getArtName() == null) ? 0 : getArtName().hashCode());
        result = prime * result + ((getArtShort() == null) ? 0 : getArtShort().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModeTime() == null) ? 0 : getLastModeTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getApproveStatus() == null) ? 0 : getApproveStatus().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCorpusId() == null) ? 0 : getCorpusId().hashCode());
        result = prime * result + ((getReadTimes() == null) ? 0 : getReadTimes().hashCode());
        result = prime * result + ((getCommentTimes() == null) ? 0 : getCommentTimes().hashCode());
        result = prime * result + ((getAdmireTimes() == null) ? 0 : getAdmireTimes().hashCode());
        result = prime * result + ((getPublishStatus() == null) ? 0 : getPublishStatus().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getArtShortPic() == null) ? 0 : getArtShortPic().hashCode());
        result = prime * result + ((getEditorType() == null) ? 0 : getEditorType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", artId=").append(artId);
        sb.append(", artName=").append(artName);
        sb.append(", artShort=").append(artShort);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastModeTime=").append(lastModeTime);
        sb.append(", status=").append(status);
        sb.append(", approveStatus=").append(approveStatus);
        sb.append(", userId=").append(userId);
        sb.append(", corpusId=").append(corpusId);
        sb.append(", readTimes=").append(readTimes);
        sb.append(", commentTimes=").append(commentTimes);
        sb.append(", admireTimes=").append(admireTimes);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", publishTime=").append(publishTime);
        sb.append(", artShortPic=").append(artShortPic);
        sb.append(", editorType=").append(editorType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}