package com.alance.blog.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlogArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public BlogArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArtIdIsNull() {
            addCriterion("ART_ID is null");
            return (Criteria) this;
        }

        public Criteria andArtIdIsNotNull() {
            addCriterion("ART_ID is not null");
            return (Criteria) this;
        }

        public Criteria andArtIdEqualTo(String value) {
            addCriterion("ART_ID =", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotEqualTo(String value) {
            addCriterion("ART_ID <>", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdGreaterThan(String value) {
            addCriterion("ART_ID >", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdGreaterThanOrEqualTo(String value) {
            addCriterion("ART_ID >=", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLessThan(String value) {
            addCriterion("ART_ID <", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLessThanOrEqualTo(String value) {
            addCriterion("ART_ID <=", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLike(String value) {
            addCriterion("ART_ID like", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotLike(String value) {
            addCriterion("ART_ID not like", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdIn(List<String> values) {
            addCriterion("ART_ID in", values, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotIn(List<String> values) {
            addCriterion("ART_ID not in", values, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdBetween(String value1, String value2) {
            addCriterion("ART_ID between", value1, value2, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotBetween(String value1, String value2) {
            addCriterion("ART_ID not between", value1, value2, "artId");
            return (Criteria) this;
        }

        public Criteria andArtNameIsNull() {
            addCriterion("ART_NAME is null");
            return (Criteria) this;
        }

        public Criteria andArtNameIsNotNull() {
            addCriterion("ART_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andArtNameEqualTo(String value) {
            addCriterion("ART_NAME =", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameNotEqualTo(String value) {
            addCriterion("ART_NAME <>", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameGreaterThan(String value) {
            addCriterion("ART_NAME >", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameGreaterThanOrEqualTo(String value) {
            addCriterion("ART_NAME >=", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameLessThan(String value) {
            addCriterion("ART_NAME <", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameLessThanOrEqualTo(String value) {
            addCriterion("ART_NAME <=", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameLike(String value) {
            addCriterion("ART_NAME like", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameNotLike(String value) {
            addCriterion("ART_NAME not like", value, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameIn(List<String> values) {
            addCriterion("ART_NAME in", values, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameNotIn(List<String> values) {
            addCriterion("ART_NAME not in", values, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameBetween(String value1, String value2) {
            addCriterion("ART_NAME between", value1, value2, "artName");
            return (Criteria) this;
        }

        public Criteria andArtNameNotBetween(String value1, String value2) {
            addCriterion("ART_NAME not between", value1, value2, "artName");
            return (Criteria) this;
        }

        public Criteria andArtShortIsNull() {
            addCriterion("ART_SHORT is null");
            return (Criteria) this;
        }

        public Criteria andArtShortIsNotNull() {
            addCriterion("ART_SHORT is not null");
            return (Criteria) this;
        }

        public Criteria andArtShortEqualTo(String value) {
            addCriterion("ART_SHORT =", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortNotEqualTo(String value) {
            addCriterion("ART_SHORT <>", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortGreaterThan(String value) {
            addCriterion("ART_SHORT >", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortGreaterThanOrEqualTo(String value) {
            addCriterion("ART_SHORT >=", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortLessThan(String value) {
            addCriterion("ART_SHORT <", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortLessThanOrEqualTo(String value) {
            addCriterion("ART_SHORT <=", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortLike(String value) {
            addCriterion("ART_SHORT like", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortNotLike(String value) {
            addCriterion("ART_SHORT not like", value, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortIn(List<String> values) {
            addCriterion("ART_SHORT in", values, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortNotIn(List<String> values) {
            addCriterion("ART_SHORT not in", values, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortBetween(String value1, String value2) {
            addCriterion("ART_SHORT between", value1, value2, "artShort");
            return (Criteria) this;
        }

        public Criteria andArtShortNotBetween(String value1, String value2) {
            addCriterion("ART_SHORT not between", value1, value2, "artShort");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeIsNull() {
            addCriterion("LAST_MODE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeIsNotNull() {
            addCriterion("LAST_MODE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeEqualTo(Date value) {
            addCriterion("LAST_MODE_TIME =", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeNotEqualTo(Date value) {
            addCriterion("LAST_MODE_TIME <>", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeGreaterThan(Date value) {
            addCriterion("LAST_MODE_TIME >", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_MODE_TIME >=", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeLessThan(Date value) {
            addCriterion("LAST_MODE_TIME <", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_MODE_TIME <=", value, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeIn(List<Date> values) {
            addCriterion("LAST_MODE_TIME in", values, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeNotIn(List<Date> values) {
            addCriterion("LAST_MODE_TIME not in", values, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_MODE_TIME between", value1, value2, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andLastModeTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_MODE_TIME not between", value1, value2, "lastModeTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andApproveStatusIsNull() {
            addCriterion("APPROVE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andApproveStatusIsNotNull() {
            addCriterion("APPROVE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andApproveStatusEqualTo(Integer value) {
            addCriterion("APPROVE_STATUS =", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusNotEqualTo(Integer value) {
            addCriterion("APPROVE_STATUS <>", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusGreaterThan(Integer value) {
            addCriterion("APPROVE_STATUS >", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPROVE_STATUS >=", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusLessThan(Integer value) {
            addCriterion("APPROVE_STATUS <", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusLessThanOrEqualTo(Integer value) {
            addCriterion("APPROVE_STATUS <=", value, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusIn(List<Integer> values) {
            addCriterion("APPROVE_STATUS in", values, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusNotIn(List<Integer> values) {
            addCriterion("APPROVE_STATUS not in", values, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusBetween(Integer value1, Integer value2) {
            addCriterion("APPROVE_STATUS between", value1, value2, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andApproveStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("APPROVE_STATUS not between", value1, value2, "approveStatus");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIsNull() {
            addCriterion("CORPUS_ID is null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIsNotNull() {
            addCriterion("CORPUS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdEqualTo(String value) {
            addCriterion("CORPUS_ID =", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotEqualTo(String value) {
            addCriterion("CORPUS_ID <>", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThan(String value) {
            addCriterion("CORPUS_ID >", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThanOrEqualTo(String value) {
            addCriterion("CORPUS_ID >=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThan(String value) {
            addCriterion("CORPUS_ID <", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThanOrEqualTo(String value) {
            addCriterion("CORPUS_ID <=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLike(String value) {
            addCriterion("CORPUS_ID like", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotLike(String value) {
            addCriterion("CORPUS_ID not like", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIn(List<String> values) {
            addCriterion("CORPUS_ID in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotIn(List<String> values) {
            addCriterion("CORPUS_ID not in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdBetween(String value1, String value2) {
            addCriterion("CORPUS_ID between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotBetween(String value1, String value2) {
            addCriterion("CORPUS_ID not between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andReadTimesIsNull() {
            addCriterion("READ_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andReadTimesIsNotNull() {
            addCriterion("READ_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andReadTimesEqualTo(Integer value) {
            addCriterion("READ_TIMES =", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesNotEqualTo(Integer value) {
            addCriterion("READ_TIMES <>", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesGreaterThan(Integer value) {
            addCriterion("READ_TIMES >", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("READ_TIMES >=", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesLessThan(Integer value) {
            addCriterion("READ_TIMES <", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesLessThanOrEqualTo(Integer value) {
            addCriterion("READ_TIMES <=", value, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesIn(List<Integer> values) {
            addCriterion("READ_TIMES in", values, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesNotIn(List<Integer> values) {
            addCriterion("READ_TIMES not in", values, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesBetween(Integer value1, Integer value2) {
            addCriterion("READ_TIMES between", value1, value2, "readTimes");
            return (Criteria) this;
        }

        public Criteria andReadTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("READ_TIMES not between", value1, value2, "readTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesIsNull() {
            addCriterion("COMMENT_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andCommentTimesIsNotNull() {
            addCriterion("COMMENT_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andCommentTimesEqualTo(Integer value) {
            addCriterion("COMMENT_TIMES =", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesNotEqualTo(Integer value) {
            addCriterion("COMMENT_TIMES <>", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesGreaterThan(Integer value) {
            addCriterion("COMMENT_TIMES >", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_TIMES >=", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesLessThan(Integer value) {
            addCriterion("COMMENT_TIMES <", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesLessThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_TIMES <=", value, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesIn(List<Integer> values) {
            addCriterion("COMMENT_TIMES in", values, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesNotIn(List<Integer> values) {
            addCriterion("COMMENT_TIMES not in", values, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_TIMES between", value1, value2, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andCommentTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_TIMES not between", value1, value2, "commentTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesIsNull() {
            addCriterion("ADMIRE_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesIsNotNull() {
            addCriterion("ADMIRE_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesEqualTo(Integer value) {
            addCriterion("ADMIRE_TIMES =", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesNotEqualTo(Integer value) {
            addCriterion("ADMIRE_TIMES <>", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesGreaterThan(Integer value) {
            addCriterion("ADMIRE_TIMES >", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("ADMIRE_TIMES >=", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesLessThan(Integer value) {
            addCriterion("ADMIRE_TIMES <", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesLessThanOrEqualTo(Integer value) {
            addCriterion("ADMIRE_TIMES <=", value, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesIn(List<Integer> values) {
            addCriterion("ADMIRE_TIMES in", values, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesNotIn(List<Integer> values) {
            addCriterion("ADMIRE_TIMES not in", values, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesBetween(Integer value1, Integer value2) {
            addCriterion("ADMIRE_TIMES between", value1, value2, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andAdmireTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("ADMIRE_TIMES not between", value1, value2, "admireTimes");
            return (Criteria) this;
        }

        public Criteria andPublishStatusIsNull() {
            addCriterion("PUBLISH_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPublishStatusIsNotNull() {
            addCriterion("PUBLISH_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPublishStatusEqualTo(Integer value) {
            addCriterion("PUBLISH_STATUS =", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusNotEqualTo(Integer value) {
            addCriterion("PUBLISH_STATUS <>", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusGreaterThan(Integer value) {
            addCriterion("PUBLISH_STATUS >", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("PUBLISH_STATUS >=", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusLessThan(Integer value) {
            addCriterion("PUBLISH_STATUS <", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusLessThanOrEqualTo(Integer value) {
            addCriterion("PUBLISH_STATUS <=", value, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusIn(List<Integer> values) {
            addCriterion("PUBLISH_STATUS in", values, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusNotIn(List<Integer> values) {
            addCriterion("PUBLISH_STATUS not in", values, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusBetween(Integer value1, Integer value2) {
            addCriterion("PUBLISH_STATUS between", value1, value2, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("PUBLISH_STATUS not between", value1, value2, "publishStatus");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("PUBLISH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("PUBLISH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("PUBLISH_TIME =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("PUBLISH_TIME <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("PUBLISH_TIME >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PUBLISH_TIME >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("PUBLISH_TIME <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("PUBLISH_TIME <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("PUBLISH_TIME in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("PUBLISH_TIME not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("PUBLISH_TIME between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("PUBLISH_TIME not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andArtShortPicIsNull() {
            addCriterion("ART_SHORT_PIC is null");
            return (Criteria) this;
        }

        public Criteria andArtShortPicIsNotNull() {
            addCriterion("ART_SHORT_PIC is not null");
            return (Criteria) this;
        }

        public Criteria andArtShortPicEqualTo(String value) {
            addCriterion("ART_SHORT_PIC =", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicNotEqualTo(String value) {
            addCriterion("ART_SHORT_PIC <>", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicGreaterThan(String value) {
            addCriterion("ART_SHORT_PIC >", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicGreaterThanOrEqualTo(String value) {
            addCriterion("ART_SHORT_PIC >=", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicLessThan(String value) {
            addCriterion("ART_SHORT_PIC <", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicLessThanOrEqualTo(String value) {
            addCriterion("ART_SHORT_PIC <=", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicLike(String value) {
            addCriterion("ART_SHORT_PIC like", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicNotLike(String value) {
            addCriterion("ART_SHORT_PIC not like", value, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicIn(List<String> values) {
            addCriterion("ART_SHORT_PIC in", values, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicNotIn(List<String> values) {
            addCriterion("ART_SHORT_PIC not in", values, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicBetween(String value1, String value2) {
            addCriterion("ART_SHORT_PIC between", value1, value2, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andArtShortPicNotBetween(String value1, String value2) {
            addCriterion("ART_SHORT_PIC not between", value1, value2, "artShortPic");
            return (Criteria) this;
        }

        public Criteria andEditorTypeIsNull() {
            addCriterion("EDITOR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEditorTypeIsNotNull() {
            addCriterion("EDITOR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEditorTypeEqualTo(Integer value) {
            addCriterion("EDITOR_TYPE =", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeNotEqualTo(Integer value) {
            addCriterion("EDITOR_TYPE <>", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeGreaterThan(Integer value) {
            addCriterion("EDITOR_TYPE >", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("EDITOR_TYPE >=", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeLessThan(Integer value) {
            addCriterion("EDITOR_TYPE <", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeLessThanOrEqualTo(Integer value) {
            addCriterion("EDITOR_TYPE <=", value, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeIn(List<Integer> values) {
            addCriterion("EDITOR_TYPE in", values, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeNotIn(List<Integer> values) {
            addCriterion("EDITOR_TYPE not in", values, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeBetween(Integer value1, Integer value2) {
            addCriterion("EDITOR_TYPE between", value1, value2, "editorType");
            return (Criteria) this;
        }

        public Criteria andEditorTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("EDITOR_TYPE not between", value1, value2, "editorType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_article
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}