package com.alance.blog.entity;

import java.io.Serializable;

public class SysDataDicKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.DIC_GROUP
     *
     * @mbggenerated
     */
    private String dicGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_data_dic.DIC_KEY
     *
     * @mbggenerated
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.DIC_GROUP
     *
     * @return the value of sys_data_dic.DIC_GROUP
     *
     * @mbggenerated
     */
    public String getDicGroup() {
        return dicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.DIC_GROUP
     *
     * @param dicGroup the value for sys_data_dic.DIC_GROUP
     *
     * @mbggenerated
     */
    public void setDicGroup(String dicGroup) {
        this.dicGroup = dicGroup == null ? null : dicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.DIC_KEY
     *
     * @return the value of sys_data_dic.DIC_KEY
     *
     * @mbggenerated
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.DIC_KEY
     *
     * @param dicKey the value for sys_data_dic.DIC_KEY
     *
     * @mbggenerated
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey == null ? null : dicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDataDicKey other = (SysDataDicKey) that;
        return (this.getDicGroup() == null ? other.getDicGroup() == null : this.getDicGroup().equals(other.getDicGroup()))
            && (this.getDicKey() == null ? other.getDicKey() == null : this.getDicKey().equals(other.getDicKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDicGroup() == null) ? 0 : getDicGroup().hashCode());
        result = prime * result + ((getDicKey() == null) ? 0 : getDicKey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicGroup=").append(dicGroup);
        sb.append(", dicKey=").append(dicKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}