package com.asher.blog.mapper;

import com.asher.blog.entity.BlogArticleContent;
import com.asher.blog.entity.BlogArticleContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * @author alance
 */
@Repository
public interface BlogArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int countByExample(BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int deleteByExample(BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int insert(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int insertSelective(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    List<BlogArticleContent> selectByExampleWithBLOBs(BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    List<BlogArticleContent> selectByExample(BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    BlogArticleContent selectByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogArticleContent record, @Param("example") BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BlogArticleContent record, @Param("example") BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogArticleContent record, @Param("example") BlogArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BlogArticleContent record);
}