package com.asher.blog.mapper;

import com.asher.blog.entity.BlogRole;
import com.asher.blog.entity.BlogRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * @author alance
 */
@Repository
public interface BlogRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int countByExample(BlogRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int deleteByExample(BlogRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int insert(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int insertSelective(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    List<BlogRole> selectByExample(BlogRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    BlogRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogRole record, @Param("example") BlogRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogRole record, @Param("example") BlogRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogRole record);
}