package com.asher.blog.mapper;

import com.asher.blog.entity.BlogArticleTagExample;
import com.asher.blog.entity.BlogArticleTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * @author alance
 */
@Repository
public interface BlogArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int countByExample(BlogArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int deleteByExample(BlogArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BlogArticleTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int insert(BlogArticleTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int insertSelective(BlogArticleTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    List<BlogArticleTagKey> selectByExample(BlogArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlogArticleTagKey record, @Param("example") BlogArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlogArticleTagKey record, @Param("example") BlogArticleTagExample example);
}