package com.asher.blog.mapper;

import com.asher.blog.entity.BlogArticle;
import org.springframework.stereotype.Repository;

/**
 * 文章-数据持久层接口
 * @author yanlong
 */
@Repository
public interface BlogArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    int insert(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    int insertSelective(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    BlogArticle selectByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogArticle record);
}